2021-03-19 13:48:11,066 [main] ERROR [com.zhongtai.pidata.PIConnection:com.zhongtai.pidata.PIConnection.getPIConnection(PIConnection.java:47)] - PI数据库连接失败.....
2021-03-19 13:48:11,084 [main] ERROR [com.zhongtai.pidata.PIConnection:com.zhongtai.pidata.PIConnection.getPIConnection(PIConnection.java:48)] - Connection failed. Please make sure the PI SQL DAS service is running, and you have supplied the correct port number. Connection timed out: connect
2021-03-19 13:48:11,084 [main] INFO  [com.zhongtai.pidata.PIConnection:com.zhongtai.pidata.PIConnection.getPIConnection(PIConnection.java:49)] - 进行重新连接PI数据库。。。。。。。。。
2021-03-19 13:48:32,092 [main] ERROR [com.zhongtai.pidata.PIConnection:com.zhongtai.pidata.PIConnection.getPIConnection(PIConnection.java:47)] - PI数据库连接失败.....
2021-03-19 13:48:32,097 [main] ERROR [com.zhongtai.pidata.PIConnection:com.zhongtai.pidata.PIConnection.getPIConnection(PIConnection.java:48)] - Connection failed. Please make sure the PI SQL DAS service is running, and you have supplied the correct port number. Connection timed out: connect
2021-03-19 13:48:32,098 [main] INFO  [com.zhongtai.pidata.PIConnection:com.zhongtai.pidata.PIConnection.getPIConnection(PIConnection.java:49)] - 进行重新连接PI数据库。。。。。。。。。
2021-03-19 13:48:53,102 [main] ERROR [com.zhongtai.pidata.PIConnection:com.zhongtai.pidata.PIConnection.getPIConnection(PIConnection.java:47)] - PI数据库连接失败.....
2021-03-19 13:48:53,102 [main] ERROR [com.zhongtai.pidata.PIConnection:com.zhongtai.pidata.PIConnection.getPIConnection(PIConnection.java:48)] - Connection failed. Please make sure the PI SQL DAS service is running, and you have supplied the correct port number. Connection timed out: connect
2021-03-19 13:48:53,102 [main] INFO  [com.zhongtai.pidata.PIConnection:com.zhongtai.pidata.PIConnection.getPIConnection(PIConnection.java:49)] - 进行重新连接PI数据库。。。。。。。。。
2021-03-19 13:49:14,108 [main] ERROR [com.zhongtai.pidata.PIConnection:com.zhongtai.pidata.PIConnection.getPIConnection(PIConnection.java:47)] - PI数据库连接失败.....
2021-03-19 13:49:14,108 [main] ERROR [com.zhongtai.pidata.PIConnection:com.zhongtai.pidata.PIConnection.getPIConnection(PIConnection.java:48)] - Connection failed. Please make sure the PI SQL DAS service is running, and you have supplied the correct port number. Connection timed out: connect
2021-03-19 13:49:14,108 [main] INFO  [com.zhongtai.pidata.PIConnection:com.zhongtai.pidata.PIConnection.getPIConnection(PIConnection.java:49)] - 进行重新连接PI数据库。。。。。。。。。
2021-03-19 13:49:35,124 [main] ERROR [com.zhongtai.pidata.PIConnection:com.zhongtai.pidata.PIConnection.getPIConnection(PIConnection.java:47)] - PI数据库连接失败.....
2021-03-19 13:49:35,124 [main] ERROR [com.zhongtai.pidata.PIConnection:com.zhongtai.pidata.PIConnection.getPIConnection(PIConnection.java:48)] - Connection failed. Please make sure the PI SQL DAS service is running, and you have supplied the correct port number. Connection timed out: connect
2021-03-19 13:49:35,129 [main] INFO  [com.zhongtai.pidata.PIConnection:com.zhongtai.pidata.PIConnection.getPIConnection(PIConnection.java:49)] - 进行重新连接PI数据库。。。。。。。。。
2021-03-19 13:49:56,131 [main] ERROR [com.zhongtai.pidata.PIConnection:com.zhongtai.pidata.PIConnection.getPIConnection(PIConnection.java:47)] - PI数据库连接失败.....
2021-03-19 13:49:56,137 [main] ERROR [com.zhongtai.pidata.PIConnection:com.zhongtai.pidata.PIConnection.getPIConnection(PIConnection.java:48)] - Connection failed. Please make sure the PI SQL DAS service is running, and you have supplied the correct port number. Connection timed out: connect
2021-03-19 13:49:56,137 [main] INFO  [com.zhongtai.pidata.PIConnection:com.zhongtai.pidata.PIConnection.getPIConnection(PIConnection.java:49)] - 进行重新连接PI数据库。。。。。。。。。
2021-03-19 13:50:17,142 [main] ERROR [com.zhongtai.pidata.PIConnection:com.zhongtai.pidata.PIConnection.getPIConnection(PIConnection.java:47)] - PI数据库连接失败.....
2021-03-19 13:50:17,142 [main] ERROR [com.zhongtai.pidata.PIConnection:com.zhongtai.pidata.PIConnection.getPIConnection(PIConnection.java:48)] - Connection failed. Please make sure the PI SQL DAS service is running, and you have supplied the correct port number. Connection timed out: connect
2021-03-19 13:50:17,142 [main] INFO  [com.zhongtai.pidata.PIConnection:com.zhongtai.pidata.PIConnection.getPIConnection(PIConnection.java:49)] - 进行重新连接PI数据库。。。。。。。。。
2021-03-19 13:50:38,147 [main] ERROR [com.zhongtai.pidata.PIConnection:com.zhongtai.pidata.PIConnection.getPIConnection(PIConnection.java:47)] - PI数据库连接失败.....
2021-03-19 13:50:38,147 [main] ERROR [com.zhongtai.pidata.PIConnection:com.zhongtai.pidata.PIConnection.getPIConnection(PIConnection.java:48)] - Connection failed. Please make sure the PI SQL DAS service is running, and you have supplied the correct port number. Connection timed out: connect
2021-03-19 13:50:38,148 [main] INFO  [com.zhongtai.pidata.PIConnection:com.zhongtai.pidata.PIConnection.getPIConnection(PIConnection.java:49)] - 进行重新连接PI数据库。。。。。。。。。
2021-03-19 13:50:59,155 [main] ERROR [com.zhongtai.pidata.PIConnection:com.zhongtai.pidata.PIConnection.getPIConnection(PIConnection.java:47)] - PI数据库连接失败.....
2021-03-19 13:50:59,155 [main] ERROR [com.zhongtai.pidata.PIConnection:com.zhongtai.pidata.PIConnection.getPIConnection(PIConnection.java:48)] - Connection failed. Please make sure the PI SQL DAS service is running, and you have supplied the correct port number. Connection timed out: connect
2021-03-19 13:50:59,156 [main] INFO  [com.zhongtai.pidata.PIConnection:com.zhongtai.pidata.PIConnection.getPIConnection(PIConnection.java:49)] - 进行重新连接PI数据库。。。。。。。。。
2021-03-19 13:51:20,171 [main] ERROR [com.zhongtai.pidata.PIConnection:com.zhongtai.pidata.PIConnection.getPIConnection(PIConnection.java:47)] - PI数据库连接失败.....
2021-03-19 13:51:20,195 [main] ERROR [com.zhongtai.pidata.PIConnection:com.zhongtai.pidata.PIConnection.getPIConnection(PIConnection.java:48)] - Connection failed. Please make sure the PI SQL DAS service is running, and you have supplied the correct port number. Connection timed out: connect
2021-03-19 13:51:20,195 [main] INFO  [com.zhongtai.pidata.PIConnection:com.zhongtai.pidata.PIConnection.getPIConnection(PIConnection.java:49)] - 进行重新连接PI数据库。。。。。。。。。
2021-03-19 13:51:41,204 [main] ERROR [com.zhongtai.pidata.PIConnection:com.zhongtai.pidata.PIConnection.getPIConnection(PIConnection.java:47)] - PI数据库连接失败.....
2021-03-19 13:51:41,205 [main] ERROR [com.zhongtai.pidata.PIConnection:com.zhongtai.pidata.PIConnection.getPIConnection(PIConnection.java:48)] - Connection failed. Please make sure the PI SQL DAS service is running, and you have supplied the correct port number. Connection timed out: connect
2021-03-19 13:51:41,205 [main] INFO  [com.zhongtai.pidata.PIConnection:com.zhongtai.pidata.PIConnection.getPIConnection(PIConnection.java:49)] - 进行重新连接PI数据库。。。。。。。。。
2021-03-19 13:52:02,213 [main] ERROR [com.zhongtai.pidata.PIConnection:com.zhongtai.pidata.PIConnection.getPIConnection(PIConnection.java:47)] - PI数据库连接失败.....
2021-03-19 13:52:02,213 [main] ERROR [com.zhongtai.pidata.PIConnection:com.zhongtai.pidata.PIConnection.getPIConnection(PIConnection.java:48)] - Connection failed. Please make sure the PI SQL DAS service is running, and you have supplied the correct port number. Connection timed out: connect
2021-03-19 13:52:02,213 [main] INFO  [com.zhongtai.pidata.PIConnection:com.zhongtai.pidata.PIConnection.getPIConnection(PIConnection.java:49)] - 进行重新连接PI数据库。。。。。。。。。
2021-03-19 13:53:07,590 [main] ERROR [com.zhongtai.pidata.PIConnection:com.zhongtai.pidata.PIConnection.getPIConnection(PIConnection.java:47)] - PI数据库连接失败.....
2021-03-19 13:53:07,592 [main] ERROR [com.zhongtai.pidata.PIConnection:com.zhongtai.pidata.PIConnection.getPIConnection(PIConnection.java:48)] - Connection failed. Please make sure the PI SQL DAS service is running, and you have supplied the correct port number. Connection timed out: connect
2021-03-19 13:53:07,592 [main] INFO  [com.zhongtai.pidata.PIConnection:com.zhongtai.pidata.PIConnection.getPIConnection(PIConnection.java:49)] - 进行重新连接PI数据库。。。。。。。。。
2021-03-19 13:53:28,599 [main] ERROR [com.zhongtai.pidata.PIConnection:com.zhongtai.pidata.PIConnection.getPIConnection(PIConnection.java:47)] - PI数据库连接失败.....
2021-03-19 13:53:28,599 [main] ERROR [com.zhongtai.pidata.PIConnection:com.zhongtai.pidata.PIConnection.getPIConnection(PIConnection.java:48)] - Connection failed. Please make sure the PI SQL DAS service is running, and you have supplied the correct port number. Connection timed out: connect
2021-03-19 13:53:28,600 [main] INFO  [com.zhongtai.pidata.PIConnection:com.zhongtai.pidata.PIConnection.getPIConnection(PIConnection.java:49)] - 进行重新连接PI数据库。。。。。。。。。
