2021-03-25 14:29:56,362 [main] ERROR [com.zhongtai.pidata.PIConnection:com.zhongtai.pidata.PIConnection.getPIConnection(PIConnection.java:47)] - PI数据库连接失败.....
2021-03-25 14:29:56,381 [main] ERROR [com.zhongtai.pidata.PIConnection:com.zhongtai.pidata.PIConnection.getPIConnection(PIConnection.java:48)] - Connection failed. Please make sure the PI SQL DAS service is running, and you have supplied the correct port number. Connection timed out: connect
2021-03-25 14:29:56,381 [main] INFO  [com.zhongtai.pidata.PIConnection:com.zhongtai.pidata.PIConnection.getPIConnection(PIConnection.java:49)] - 进行重新连接PI数据库。。。。。。。。。
2021-03-25 14:32:04,382 [main] ERROR [com.zhongtai.pidata.PIConnection:com.zhongtai.pidata.PIConnection.getPIConnection(PIConnection.java:47)] - PI数据库连接失败.....
2021-03-25 14:32:04,395 [main] ERROR [com.zhongtai.pidata.PIConnection:com.zhongtai.pidata.PIConnection.getPIConnection(PIConnection.java:48)] - Connection failed. Please make sure the PI SQL DAS service is running, and you have supplied the correct port number. Connection timed out: connect
2021-03-25 14:32:04,395 [main] INFO  [com.zhongtai.pidata.PIConnection:com.zhongtai.pidata.PIConnection.getPIConnection(PIConnection.java:49)] - 进行重新连接PI数据库。。。。。。。。。
2021-03-25 14:32:25,404 [main] ERROR [com.zhongtai.pidata.PIConnection:com.zhongtai.pidata.PIConnection.getPIConnection(PIConnection.java:47)] - PI数据库连接失败.....
2021-03-25 14:32:25,404 [main] ERROR [com.zhongtai.pidata.PIConnection:com.zhongtai.pidata.PIConnection.getPIConnection(PIConnection.java:48)] - Connection failed. Please make sure the PI SQL DAS service is running, and you have supplied the correct port number. Connection timed out: connect
2021-03-25 14:32:25,405 [main] INFO  [com.zhongtai.pidata.PIConnection:com.zhongtai.pidata.PIConnection.getPIConnection(PIConnection.java:49)] - 进行重新连接PI数据库。。。。。。。。。
2021-03-25 14:32:57,389 [main] ERROR [com.zhongtai.pidata.PIConnection:com.zhongtai.pidata.PIConnection.getPIConnection(PIConnection.java:47)] - PI数据库连接失败.....
2021-03-25 14:32:57,399 [main] ERROR [com.zhongtai.pidata.PIConnection:com.zhongtai.pidata.PIConnection.getPIConnection(PIConnection.java:48)] - Connection failed. Please make sure the PI SQL DAS service is running, and you have supplied the correct port number. Connection timed out: connect
2021-03-25 14:32:57,400 [main] INFO  [com.zhongtai.pidata.PIConnection:com.zhongtai.pidata.PIConnection.getPIConnection(PIConnection.java:49)] - 进行重新连接PI数据库。。。。。。。。。
